sudo: false
language: node_js
cache: npm
  directories:
    - node_modules
node_js:
  - '8'
before_install:
  - npm update
install:
  - npm install
  script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - gh-pages
    - /.*/
